- name: Install PostgreSQL dependencies
  action: apt pkg={{item}} state=latest
  with_items:
  - python-pycurl
  - python-psycopg2

- name: Add postgres latest version ppa
  action: apt_repository repo=ppa:pitti/postgresql

- name: Update APT cache
  action: apt update_cache=yes

- name: Install db server packages
  action: apt pkg={{ item }} state=present
  with_items:
  - postgresql
  - postgresql-contrib
  - postgresql-common